FROM debian:11

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
    nginx-full libnginx-mod-http-fancyindex libnginx-mod-http-dav-ext \
    libnginx-mod-http-lua luarocks lua-ljsyscall lua-penlight \
    && apt-get autoremove && apt-get clean

RUN mkdir -p /mnt/data && mkdir /mnt/tmp && chmod -R a+rwx /mnt

# redirect logs to stdout/err
RUN ln -sf /dev/stdout /var/log/nginx/access.log && \
    ln -sf /dev/stderr /var/log/nginx/error.log

# remove default handler
RUN rm /etc/nginx/sites-enabled/default

# copy in new default config
COPY nginx_config/nginx_default.conf /etc/nginx/nginx.conf

# override this for customization (listen port, auth proxy, health)
COPY nginx_config/auth.conf /etc/nginx/custom/auth.conf
COPY nginx_config/health.conf /etc/nginx/sites-enabled/health.conf

# set umask
RUN echo '#!/bin/sh\numask 002\nexec $@' >> /opt/entrypoint.sh && \
    chmod +x /opt/entrypoint.sh

ENTRYPOINT ["/opt/entrypoint.sh"]

CMD ["nginx"]
