FROM debian:11

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
    nginx-full libnginx-mod-http-fancyindex libnginx-mod-http-dav-ext \
    libnginx-mod-http-lua luarocks lua-ljsyscall \
    && apt-get autoremove && apt-get clean

RUN mkdir -p /mnt/data && mkdir /mnt/tmp && chmod -R a+rwx /mnt

# redirect logs to stdout/err
RUN ln -sf /dev/stdout /var/log/nginx/access.log && \
    ln -sf /dev/stderr /var/log/nginx/error.log

# remove default handler
RUN rm /etc/nginx/sites-enabled/default

# copy in new default config
COPY nginx_default.conf /etc/nginx/nginx.conf

# override this for customization (listen port, auth proxy)
COPY nginx_config.conf /etc/nginx/custom/webdav.conf

# set umask
RUN echo "umask 002" >> /opt/bitnami/scripts/libnginx.sh

CMD ["nginx"]
