FROM debian:11

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
    nginx libnginx-mod-http-fancyindex libnginx-mod-http-dav-ext \
    libnginx-mod-http-lua luarocks lua-ljsyscall \
    && apt-get autoremove && apt-get clean

RUN mkdir /mnt/tmp && chmod -R a+rwx /mnt

# redirect logs to stdout/err
RUN ln -sf /dev/stdout /var/log/nginx/access.log && \
    ln -sf /dev/stderr /var/log/nginx/error.log

COPY nginx_default.conf /etc/nginx/nginx.conf
COPY nginx_config.conf /etc/nginx/custom.conf

CMD ["nginx"]
