name: 'Docker Nginx'

on:
  pull_request:
  push:
    branches:
      - main
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    name: "Push Docker Image"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Project
      uses: actions/checkout@v2
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-keycloak-http-auth-nginx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-keycloak-http-auth-nginx-

    - name: Docker meta
      id: docker_meta
      uses: crazy-max/ghaction-docker-meta@v2
      with:
        # list of Docker images to use as base name for tags
        images: |
          ghcr.io/WIPACRepo/keycloak-http-auth
        tags: |
            type=ref,event=branch,prefix=nginx-
            type=semver,pattern={{major}},prefix=nginx-
            type=semver,pattern={{major}}.{{minor}},prefix=nginx-
            type=semver,pattern={{major}}.{{minor}}.{{patch}},prefix=nginx-

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      if: ${{ github.event_name != 'pull_request' }}
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push Docker Image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile
        builder: ${{ steps.buildx.outputs.name }}
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache
        tags: ${{ steps.docker_meta.outputs.tags }}
        labels: ${{ steps.docker_meta.outputs.labels }}
        push: ${{ github.event_name != 'pull_request' }}
