
name: Integration tests

on:
  pull_request:
  push:
    branches:
      - main
  release:
    types: [published]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
        architecture: x86
    - name: Install dependencies
      id: dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Integration tests
      run: |
        python -m pytest integration_tests --log-level=INFO
